apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prod
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'microservices'
        scrape_interval: 15s
        metrics_path: '/metrics'
        static_configs:
          - targets:
              - 'user-service:3001'
              - 'restaurant-service:3002'
              - 'order-service:3003'
              - 'payment-service:3004'
            labels:
              group: 'microservices'

      - job_name: 'cadvisor'
        scrape_interval: 15s
        static_configs:
          - targets:
              - 'cadvisor:8080'

      - job_name: 'prometheus'
        scrape_interval: 15s
        static_configs:
          - targets:
              - 'localhost:9090'
