apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-db-pvc
  namespace: prod
  labels:
    app: restaurant-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
