apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-configmap
  namespace: prod
  labels:
    app: order-service
data:
  NODE_ENV: "production"
  PORT: "3003"
  LOG_LEVEL: "warn"
  LOG_FORMAT: "json"
  CORS_ORIGIN: "*"
  DB_HOST: "order-db-service"
  DB_PORT: "5432"
  DB_NAME: "order_service"
  DATABASE_URL: "postgresql://order_service_user:CHANGE_ME_order_db_password_789@order-db-service:5432/order_service"
  USER_SERVICE_URL: "http://user-service:3001"
  RESTAURANT_SERVICE_URL: "http://restaurant-service:3002"
  PAYMENT_SERVICE_URL: "http://payment-service:3004"
