apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-service-configmap
  namespace: prod
  labels:
    app: restaurant-service
data:
  NODE_ENV: "production"
  PORT: "3002"
  LOG_LEVEL: "warn"
  LOG_FORMAT: "json"
  CORS_ORIGIN: "*"
  DB_HOST: "restaurant-db-service"
  DB_PORT: "5432"
  DB_NAME: "restaurant_service"
  DATABASE_URL: "postgresql://restaurant_service_user:CHANGE_ME_restaurant_db_password_456@restaurant-db-service:5432/restaurant_service"
