apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: prod
  labels:
    app: user-service
data:
  NODE_ENV: "production"
  PORT: "3001"
  LOG_LEVEL: "warn"
  LOG_FORMAT: "json"
  CORS_ORIGIN: "*"
  DB_HOST: "user-db-service"
  DB_PORT: "5432"
  DB_NAME: "user_service"
  JWT_EXPIRES_IN: "1h"
  BCRYPT_SALT_ROUNDS: "10"
